#!/usr/bin/env node
// ============================================================
// sync-repos.mjs — refresh the shared repo context for agents.
// ------------------------------------------------------------
// Regenerates the machine-readable block in
// `.claude/context/account-repos.md` from the live account so agents
// always know which repos exist, their stack, and Pages status.
//
// The hand-written prose above the marker is preserved; only the
// auto-generated table below the marker is rewritten.
//
// Usage:  node scripts/sync-repos.mjs   (use --check in CI to verify it's fresh)
// ============================================================

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { ghJson, owner, listRepos } from './lib.mjs'

const DOC = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  '.claude',
  'context',
  'account-repos.md'
)
const MARKER = '<!-- AUTO:repos -->'

const account = owner()
const repos = listRepos()

function pagesUrl(name) {
  const info = ghJson(['api', `repos/${account}/${name}/pages`])
  return info?.html_url || ''
}

const rows = repos.map((r) => {
  const lang = r.primaryLanguage?.name || '—'
  const vis = r.isPrivate ? 'private' : 'public'
  const pages = pagesUrl(r.name)
  return `| [${r.name}](${r.url}) | ${lang} | ${vis} | ${r.description || ''} | ${
    pages ? `[live](${pages})` : '—'
  } |`
})

const generated = [
  MARKER,
  `<!-- regenerated by scripts/sync-repos.mjs — do not edit below this line -->`,
  '',
  `_Account: **${account}** · ${repos.length} source repos._`,
  '',
  '| Repo | Language | Visibility | Description | Pages |',
  '|------|----------|------------|-------------|-------|',
  ...rows,
  '',
].join('\n')

const existing = readFileSync(DOC, 'utf8')
const idx = existing.indexOf(MARKER)
const next =
  (idx === -1 ? existing.trimEnd() + '\n\n' : existing.slice(0, idx)) + generated

if (process.argv.includes('--check')) {
  if (next.trim() !== existing.trim()) {
    console.error('account-repos.md is stale — run `npm run repos:sync`.')
    process.exit(1)
  }
  console.log('account-repos.md is up to date.')
  process.exit(0)
}

writeFileSync(DOC, next)
console.log(`Updated ${DOC} (${repos.length} repos).`)
